### PR TITLE
Create contact.js

### PR DESCRIPTION
**Pull request by IntegraterGithub**
Not finished I made it mail your email with subject + content

### CODE REVIEW

**Comment by Milo123459** [comment]
This website is built with ReactJS, not plain JS / HTML

**Comment by Milo123459** [comment]
Actually I think I'll add this on my own

**Comment by IntegraterGithub** [comment]
I did say wasn't finished

**Comment by IntegraterGithub** [comment]
Do you want php send, or open mail

**Comment by Milo123459** [comment]
I appreciate the offer but I'll add it on my own, please finish the other PR you made.

**Pull request closed without merging**
